### ISSUE TITLE
Mid-semester check in

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [DukeStatSci/thesis-sp18-yu-reproducibility#2]
@huijiayu Please respond to the following questions in a reply to this issue by Wednesday Nov 1, 5pm. Brief answers are ok.

- What is the ultimate goal of the thesis?
- What portion of the thesis work have you completed so far?
- What parts of the analysis do you plan on completing by the end of the semester?
- What sections do you expect to include in your Fall semester write up? (Note that this is due as a gitbook and PDF output on Dec 7 at 9am, I'll take a snapshot of your repo at that time.)

**Comment by huijiayu** [comment]
- What is the ultimate goal of the thesis?
- Explore Bayesian methods for inference post-selection

- What portion of the thesis work have you completed so far?
- I have read some papers/articles and working through methods

- What parts of the analysis do you plan on completing by the end of the semester?
- Set up simulation and explore

- What sections do you expect to include in your Fall semester write up?
- Literature review, and simulations
